### ISSUE TITLE
Unable to update jira with contents in org-mode buffer

### ISSUE THREAD

**Issue by mcraveiro** [ahungry/org-jira#248] opened 2021-03-24 14:50 UTC
Hi org-jira developers,

Thanks very much for an amazing mode. I'm just learning the ropes at the moment and I must be doing something very silly. I got all my jiras downloaded locally, and they look fine; but when I try to do an ```org-jira-update-issue```, I lose all my local changes in the description and it reverts back to the version in the server. Do I need to do anything else to get it to send its changes by any chance?

Many thanks for your time.

**Comment by ahungry** [comment] 2021-03-25 01:59
@mcraveiro does anything show up in the *Messages* buffer (or other buffers)?  Such as a failed http request?

**Comment by mcraveiro** [comment] 2021-03-26 09:21
Thanks very much for the prompt resonse @ahungry. I cannot see anything obvious in Messages, though I see a lot of debug output. Unfortunately I will not be in front of my workstation until Monday but I'll paste the Messages log here to see if it provides any clues.

Cheers

**Comment by NahsiN** [comment] 2021-04-02 02:58
I've the same problem as @mcraveiro, the output of the Messages buffer is shown below

```
About to sync worklog for issue: ID-202 in file: ID
Updating worklog from org-jira-update-worklogs-from-org-clocks call
org-jira-update-worklogs-for-issue id: ID-202 filename: ID
org-jira-update-worklogs-for-issue cb id: ID-202 fn: ID
[error] request--callback: peculiar error: 400
[error] request-default-error-callback: https://*********.atlassian.net/rest/api/2/issue/ID-202 error
Issue ’ID-202’ updated!
Update get issue for refresh callback hit.
Fetching issues...
About to render 1 issues.
org-jira-update-worklogs-for-issue id: ID-202 filename: ID
org-jira-update-worklogs-for-issue cb id: ID-202 fn: ID
In the callback for org-jira-update-comments-for-issue.
Mark set
```

**Comment by ezmiller** [comment] 2021-04-06 21:09
@ahungry I have the problem where when I run `org-jira-get-issues` nothing comes into the org buffer. But I do see content in the `*Messages*` buffer.

I opened what may be a related issue: #250.

I noticed that when I run `org-jira-get-issues-headonly`, content does flow into org-buffer...

**Comment by mcraveiro** [comment] 2021-04-16 07:20
Ah interesting, I'll check my messages buffer as well.

**Comment by bhipple** [comment] 2021-05-03 16:57
I just spent a while debugging this, and made it this far: if you scroll way back in your `*Messages*` buffer, you will likely see a failure on one of the intermediate REST calls, like this:

```
{"errorMessages":[],"errors":{"assignee":"expected Object containing a 'name' property"}}
[debug] request--callback: executing error
[error] request-default-error-callback: <jira>/rest/api/2/issue/<issue> parse-error
```

It then goes on to fail to post the update, but the code continues and succeeds to download the contents, which results in the buffer revert.  I managed to get mine working by commenting out these two lines in `org-jira-update-issue-details`:

```elisp
(cons 'assignee (list (cons 'id (jiralib-get-user-account-id project org-issue-assignee))))
(cons 'reporter (list (cons 'id (jiralib-get-user-account-id project org-issue-reporter))))
```
It looks like something was going wrong with mapping between my username and my displayed full user name, with spaces.  Digging a little more, the issue is that `jiralib-get-user-account-id` does not work (returns `nil`), so I suspect the answer to this question was "no":

https://github.com/ahungry/org-jira/pull/213#issuecomment-657900405

**Comment by mcraveiro** [comment] 2021-05-06 09:28
I must be doing something wrong because my ```*Messages*``` looks very clean...

```
Saving file SOME_DIR/.org-jira/SOME_PROJECT.org...
Wrote SOME_DIR/SOME_PROJECT.org
About to sync worklog for issue: SOME_PROJECT-ISSUE_NUMBER in file: SOME_PROJECT
Issue ’SOME_PROJECT-ISSUE_NUMBER’ updated!
Update get issue for refresh callback hit.
Fetching issues...
About to render 1 issues.
org-jira-update-worklogs-for-issue id: SOME_PROJECT-ISSUE_NUMBER filename: SOME_PROJECT
org-jira-update-worklogs-for-issue cb id: SOME_PROJECT-ISSUE_NUMBER fn: SOME_PROJECT
In the callback for org-jira-update-comments-for-issue.
Saving file SOME_DIR/.org-jira/SOME_PROJECT.org...
Wrote SOME_DIR/.org-jira/SOME_PROJECT.org
```
I think I may be missing some debug variables. This is after I called ```org-jira-get-issue```, which loaded up the issue nicely, then made some test changes and tried to save those down via ```org-jira-update-issue```.

**Comment by ahungry** [comment] 2021-05-08 04:40
request.el primarily uses curl, although it may default to url.el if it isn't able to use curl.

Try out:

          (setq request-log-level 'blather)                                                                                            
          (setq request-message-level 'blather) 

That is the most verbose output for the package available.

**Comment by mcraveiro** [comment] 2021-05-10 10:28
Aha, thanks @ahungry. Once I set those variables I then got a whole load of debug output and indeed I have exactly the same issue as reported by @bhipple above - my name is coming up with spaces and I see the error on the debug dumps:

```json
{"errorMessages":[],"errors":{"assignee":"expected Object containing a 'name' property"}}
```
I will now try to use the suggested work around and see if that gets me any further.

**Comment by mcraveiro** [comment] 2021-05-10 10:36
Yep, that workaround did fix my update issues, so hurray! However :-) When I update, I now seem to have a concatenation of ```TODO```s in the title, /i.e./, it starts with:

```TODO some title```

then after an update it becomes 

```TODO TODO some title```

And it adds a ```TODO``` for each update :-) I'll check the past issues to see if I can figure out what I am doing wrong. Other than that, seems to be working ok now!

**Comment by ahungry** [comment] 2021-05-26 03:46
@bhipple this works for me - does it fail for you?

    ;; Replace my name with your first/last full name on your own Jira, and your project with your own
    (jiralib-get-user-account-id "AHU" "Matthew Carter")

I'm not sure if it will be possible to support legacy jira instances that aren't kept up to date with the cloud offering, if we are to keep up for the cloud offering.

I'm going to close this for now as there doesn't seem to be a Jira cloud reproducible failure for now.

**Closed by ahungry** 2021-05-26 03:46 UTC
