### ISSUE TITLE
Support attachments

### ISSUE THREAD

**Issue by yyoncho** [ahungry/org-jira#57] opened 2017-09-27 07:59 UTC
There is no support for ticket attachments

**Comment by yyoncho** [comment] 2017-09-27 08:13
@ahungry I would like to implement that functionality if you don't mind.

**Comment by ahungry** [comment] 2017-09-28 02:19
Sure, could be cool if you tie it into the org-mode functionality for linking files (if you plan to fetch remote attachments, I would make that part user customizable so they can opt out of they don't want to download many attachments).

**Comment by ahungry** [comment] 2017-11-14 05:33
@yyoncho I merged your PR, it is causing issues however.

Without the feature, using a call to (fresh/empty buffer): `org-jira-get-issues` and a subsequent call to `org-jira-refresh-issues-in-buffer` should provide identical results / no changes.

Unfortunately, with your change, the attachments load / apply their data *ok* with the org-jira-get-issues call, but the org-jira-refresh-issues-in-buffer call breaks it badly (duplicate attachments, not bound to the actual issue they should apply to etc.).

There is also a problem with how you used the org cut functionality - this modifies user kill ring, which is an undesirable side-effect for maintaining attachment based data (I have replaced with a custom delete subtree functionality).

For the moment, I have had to disable the call to pull in attachments, when your change fixes these issues with the refresh call, I can re-enable.

Thanks!

**Comment by yyoncho** [comment] 2017-11-14 07:15
@ahungry sorry for that, I didn't know about these function so I didn't test them. I will take a look and fix the issue.

**Comment by yyoncho** [comment] 2017-11-23 12:27
@ahungry - For some I was unable to reproduce the issue with the steps described by you (get/refresh issue). I suspect that it might be fixed by calling org-narrow-to-subtree in ensture-on-issue macro but I cannot test/verify that.

As a side note, the clipboard is polluted by using org-kill-line as well. What do you think about solving that issue globally e. g. persisting/restoring kill-ring in ensure-* macros? 

Thanks

**Comment by ahungry** [comment] 2017-11-27 15:49
Did you try the refresh all issues?  `C-c i R runs the command org-jira-refresh-issues-in-buffer` - the problem is that the attachment meta data is attached to the wrong issues, so most likely one of the excursions is not being saved or the proper issue isn't being navigated to, when this call happens asynchronously / in non-deterministic order.

Running a single issue refresh doesn't have the problem as the cursor is already in the target issue to modify.

**Closed** 2021-07-20 04:01 UTC
