### ISSUE TITLE
org-jira-update-worklogs-from-org-clocks

### ISSUE THREAD

**Issue by robwithhair** [ahungry/org-jira#104] opened 2018-07-25 10:33 UTC
when I run org-jira-update-worklogs-from-org-clocks it doesn't seem to update the open issue clocks with the correct IDs from Jira.  That means that when you run it again it duplicates worklogs on jira.  Am I missing something or is this a bug?

**Comment by nickgarber** [comment] 2018-07-29 13:10
I noticed this recently too, but hadn't had a chance to dig into when it
happened or the cause.

**Comment by akall80** [comment] 2018-07-30 12:39
Same for me.
The nice fact is that if you re-upload worklogs, Jira sees them doubled. It came up in June, with releases 3.1.0/3.1.1 . In January release it was not present.

**Comment by ahungry** [comment] 2018-07-30 20:54
I'll investigate tonight

**Comment by ahungry** [comment] 2018-07-31 13:46
Still working on this - the problem is that the request to pull worklogs is either not getting the id, or failing when it's supposed to be inserting the id under the clock entry.

As observed, it is not failing to send those entries up to Jira atm (unfortunately, all as insert vs update).

**Comment by ahungry** [comment] 2018-07-31 14:26
Fixed in tag 3.1.2 and on latest master

**Closed** 2018-08-01 02:32 UTC

**Comment by akall80** [comment] 2018-08-01 05:56
Tested and working! Sooo good, many many thanks!
