### ISSUE TITLE
Show User Name of Mentions instead of Account ID

### ISSUE THREAD

**Issue by cartesian-theatrics** [ahungry/org-jira#221] opened 2020-07-28 19:42 UTC
Hello,

I'm loving this library, thanks for all your work on it. One annoyance I'm having is currently `@` mentions just show the accountid, for example `[~accountid:557058:235559f0-b...] . Is there a way to show the user name? I also don't see a way to mention someone when creating a comment or ticket; would it be possible to add a "mention user" command?

Thanks,
John

**Comment by adrubesh** [comment] 2020-08-13 13:47
Also would love to see this!

**Comment by andcarnivorous** [comment] 2021-07-18 19:22
I started having a look into this because I would like the feature as well. I came up with some functions that parse the comments body to insert / delete the username next to the accountid.

The following is the code I added to the `org-jira.el` file.
```lisp
(defun org-jira-get-username (user)
  (org-jira-find-value user 'displayName))

(defun org-jira-match-user-id-number (account-id)
  (string-match "[0-9a-z]\\{24\\}" account-id)
  (match-string 0 account-id))

(defun org-jira-find-account-ids (comment)
  (let ((pos 0)
 matches)
    (while (string-match "\[~accountid:[0-9a-z]+\]" comment pos)
     (push (match-string 0 comment) matches)
      (setq pos (match-end 0)))
    (delete-dups matches)))


(defun org-jira-add-user-name (account-id)
   (concat account-id "_" (org-jira-get-username
        (jiralib-get-user (org-jira-match-user-id-number account-id))) "_" ))


(defun org-jira-replace-account-id (account-ids comment &optional remove-username)
  (dolist (account-id account-ids)
    (setq comment 
   (if (not remove-username)
       (replace-regexp-in-string (regexp-quote
      (format "\[~accountid:%s\]" (org-jira-match-user-id-number account-id)))
     (org-jira-add-user-name account-id) comment)
     (replace-regexp-in-string 
      (format "\\[~accountid:%s\\]_[A-Za-z ]+_" (org-jira-match-user-id-number account-id))
      account-id comment))
   ))
    comment)

(defun org-jira--render-comment (Issue Comment)
  (with-slots (issue-id) Issue
    (with-slots (comment-id author headline created updated body) Comment
      (org-jira-log (format "Rendering a comment: %s" body))
      (ensure-on-issue-Issue Issue
        (setq p (org-find-entry-with-id comment-id))
        (when (and p (>= p (point-min))
                   (<= p (point-max)))
          (goto-char p)
          (org-narrow-to-subtree)
          (delete-region (point-min) (point-max)))
        (goto-char (point-max))
        (unless (looking-at "^")
          (insert "\n"))
        (insert "*** ")
        (org-jira-insert headline "\n")
        (org-narrow-to-subtree)
        (org-jira-entry-put (point) "ID" comment-id)
        (org-jira-entry-put (point) "created" created)
        (unless (string= created updated)
          (org-jira-entry-put (point) "updated" updated))
        (goto-char (point-max))
        ;;  Insert 2 spaces of indentation so Jira markup won't cause org-markup
        (org-jira-insert 
  (replace-regexp-in-string "^" "  " ;;; MODIFIED HERE
;       (or body "")))))))
         (or (org-jira-replace-account-id (org-jira-find-account-ids body) body) "")))))))```

While these functions work on their own, when I try to implement into `org-jira--render-comment` I get some unexpected behavior and errors (among some, the `org-jira-get-username` is reported as void, although  it is defined earlier in the code)

**Comment by ahungry** [comment] 2023-03-24 00:17
I'm going to close this out due to stagnation.

**Closed by ahungry** 2023-03-24 00:17 UTC
Labels: enhancement

**Comment by eraschle** [comment] 2024-01-22 03:10
I'm still learning Lisp, and somehow I managed to adjust the names in the comments when synchronizing. I suspect that the regex pattern for the account number; as well as the search for ORG links in the string can be solved better/easier.
In the ORG files, I use the link to the user profile on Jira. A link to a query (if possible) could be an interesting alternative.
Any improvement/feedback on the code is welcome.
I have not made any pull requests yet, but I can do so if desired.
[Except for a few small adjustments, this is the solution.](https://github.com/eraschle/org-jira/commit/c591a629b3d9508a511ebfc5620b24b42fd7a747)

> I started having a look into this because I would like the feature as well. I came up with some functions that parse the comments body to insert / delete the username next to the accountid.
> 
> The following is the code I added to the `org-jira.el` file.
> 
> ```lisp
> (defun org-jira-get-username (user)
>   (org-jira-find-value user 'displayName))
> 
> (defun org-jira-match-user-id-number (account-id)
>   (string-match "[0-9a-z]\\{24\\}" account-id)
>   (match-string 0 account-id))
> 
> (defun org-jira-find-account-ids (comment)
>   (let ((pos 0) matches)
>     (while (string-match "\[~accountid:[0-9a-z]+\]" comment pos)
>      (push (match-string 0 comment) matches)
>       (setq pos (match-end 0)))
>     (delete-dups matches)))
> 
> 
> (defun org-jira-add-user-name (account-id)
>    (concat account-id "_" (org-jira-get-username
>         (jiralib-get-user (org-jira-match-user-id-number account-id))) "_" ))
> 
> 
> (defun org-jira-replace-account-id (account-ids comment &optional remove-username)
>   (dolist (account-id account-ids)
>     (setq comment 
>    (if (not remove-username)
>        (replace-regexp-in-string (regexp-quote
>       (format "\[~accountid:%s\]" (org-jira-match-user-id-number account-id)))
>      (org-jira-add-user-name account-id) comment)
>      (replace-regexp-in-string 
>       (format "\\[~accountid:%s\\]_[A-Za-z ]+_" (org-jira-match-user-id-number account-id))
>       account-id comment))))
>     comment)
> 
> (defun org-jira--render-comment (Issue Comment)
>   (with-slots (issue-id) Issue
>     (with-slots (comment-id author headline created updated body) Comment
>       (org-jira-log (format "Rendering a comment: %s" body))
>       (ensure-on-issue-Issue Issue
>         (setq p (org-find-entry-with-id comment-id))
>         (when (and p (>= p (point-min))
>                    (<= p (point-max)))
>           (goto-char p)
>           (org-narrow-to-subtree)
>           (delete-region (point-min) (point-max)))
>         (goto-char (point-max))
>         (unless (looking-at "^")
>           (insert "\n"))
>         (insert "*** ")
>         (org-jira-insert headline "\n")
>         (org-narrow-to-subtree)
>         (org-jira-entry-put (point) "ID" comment-id)
>         (org-jira-entry-put (point) "created" created)
>         (unless (string= created updated)
>           (org-jira-entry-put (point) "updated" updated))
>         (goto-char (point-max))
>         ;;  Insert 2 spaces of indentation so Jira markup won't cause org-markup
>         (org-jira-insert 
>   (replace-regexp-in-string "^" "  " ;;; MODIFIED HERE
> ;       (or body "")))))))
>          (or (org-jira-replace-account-id (org-jira-find-account-ids body) body) "")))))))
> ```
> 
> While these functions work on their own, when I try to implement into `org-jira--render-comment` I get some unexpected behavior and errors (among some, the `org-jira-get-username` is reported as void, although it is defined earlier in the code). Before keeping going ahead with this however, I'd like to know if the approach I'm taking could be considered to implement the feature.
