### ISSUE TITLE
org-jira-update-issue fails with "No project with the provided key exists"

### ISSUE THREAD

**Issue by mruediger** [ahungry/org-jira#235] opened 2020-10-23 15:52 UTC
Hey there.

When ever I run `org-jira-update-issue` I am getting the following error message:

```
About to sync worklog for issue: DSP-6752 in file: DSP
jiralib-get-user-account-id: Wrong type argument: listp, (errorMessages . ["No project with the provided key exists"])
```
Can anyone help me on debugging this issue? I am pretty new to `emacs` and `org-jira` and don't know were to start but would be very grateful if someone would point me into the right direction.

**Comment by AblatedSprocket** [comment] 2020-11-17 22:46
I'm seeing the same thing.

**Comment by ahungry** [comment] 2020-11-18 21:17
ffdb3e39 appears to have introduced the function jiralib-get-user-account-id, which was from a PR I accepted having to do with getting account ids - I'm not sure if this is related.

**Comment by ahungry** [comment] 2020-11-19 01:47
Yes, that seems to be the commit that caused the issue.  The problem is that jiralib-get-user-account-id is passing nil instead of a valid project-key when calling jiralib-get-users, and that is not a valid input.

It likely was not discovered previously, as other actions will cause jiralib-get-users to be called *with* a valid project key, in which case the list of users becomes cached in jiralib-users-cache and the invalid call with nil is not performed.

**Comment by ahungry** [comment] 2020-11-19 01:54
Fixed in df45be1

**Closed by ahungry** 2020-11-19 01:54 UTC
