### ISSUE TITLE
Rest API differences between Jira Cloud and Jira Server Platforms

### ISSUE THREAD

**Issue by 0l1ve** [ahungry/org-jira#287] opened 2022-03-02 11:02 UTC
The current org-jira codebase appears to be using only the Cloud Rest API's.  That means that several functions break when the Jira instance being used is not an atlassian cloud hosted instance but a Server platform instance in a datacenter.

So far the main difference/issue's I have identified are:

1. Creating a new Jira issue fails silently due to the `assigneeID` field not being valid in the JSON.  Server platform uses the field `name`.  It fails even when creating a new issue without an initial assignee. (Fixed in Fork)
2. Updating the assignee on an issue fails as the Server Platform API is expecting the `name` value instead of an ID value. (Fixed in Fork)

(Main api differences seem to be Server Platform not using id's in the assignee and reporter fields so far)

I have created a fork of this repository and pushed the fixes I have implemented to that fork (https://github.com/0l1ve/org-jira.git).

The fixes entail some minor changes and a new boolean variable to toggle which API to use.  The default toggle uses the cloud API calls.

I will continue with this fork as I find issues.  If you agree with my changes or have a better way of handling them I would then feel free to include/change them.

**Comment by ahungry** [comment] 2022-03-02 14:00
Looks interesting - I'm hesitant to include/support, as I don't have a way to test these changes/discrepancies between Jira instances, so I'll leave this open while more people chime in about a desire to have this (and willingness to support) vs not.

General critique/suggestion - I would avoid duplicating inlined blocks as you did in most divergent areas, as (in lisp in particular) large `IF` blocks can be difficult to read, and in the below sample, the only difference is a symbol, meaning the two blocks could change from this:

```lisp
(defun jiralib-get-user-account-id (project full-name)
  "Return the account-id (accountId) of the user with FULL-NAME (displayName) in PROJECT."
  (if jiralib-cloud-enabled
      (cl-loop for user in (jiralib-get-users project)
               when (rassoc full-name user)
               return (cdr (assoc 'accountId user)))
    (cl-loop for user in (jiralib-get-users project)
             when (rassoc full-name user)
             return (cdr (assoc 'name user)))))
```

to something like this:
```
(defun org-jira--get-account-id-sym () 
  (if jiralib-cloud-enabled 'account-id 'name))

(defun jiralib-get-user-account-id (project full-name)
    "Return the account-id (accountId) of the user with FULL-NAME (displayName) in PROJECT."
  (cl-loop for user in (jiralib-get-users project)
        when (rassoc full-name user)
        return (cdr (assoc (org-jira--get-account-id-sym) user))))
```

Something like that (a simple accessor) tends to make it more testable/future-proof as well, in particular if the extent of difference between the two systems tends to be key names.

**Comment by ahungry** [comment] 2022-03-02 14:02
Another thing to consider - is the discrepancy due to on-prem vs cloud, or simply that your on-prem is at an earlier version than cloud?

It seems odd to me that they would break their own API compatability for self hosted vs cloud reasons, when it may just be version mismatch?

**Comment by 0l1ve** [comment] 2022-03-02 19:57
If you are interested, I refactored the code based upon your tip and also corrected org-jira-set-issue-reporter as well inline with this issue.

So far I have not found any other differences/broken functions for me at least.

**Comment by ahungry** [comment] 2022-03-02 21:38
Nice, although I think there may be regressions with cloud in your current branch - you've replaced 3 different symbols with one - in the old code, there was `accountId`, `account-id` and `id` - which are now all replaced with `accountId` (while these may all map cleanly to `name` on the old version.

You could make 3 versions of the helper function, or perhaps modify it similar to:

```
(defun jiralib--get-account-sym (cloud-sym)
  (if org-jira-cloud-mode cloud-sym 'name))
```

Then just replace the removed lines to be similar to this:
```
(jiralib--get-account-sym 'accountId)
(jiralib--get-account-sym 'account-id)
(jiralib--get-account-sym 'id)
```
as necessary.

Granted, it won't matter for you (if doing just on-prem), but it highlights another maintenance burden with the approach - anyone working on the code may only be working/testing from one of two use cases (and I would guess it's rare someone has both on-prem and cloud available, further minimizing the pool of people who can actually test changes under both cases).

Last Emacs lisp/package advice - any function that's "internal" and not meant to be used by users of the package should use the double dash - `jiralib-get-account-sym` implies anyone can start adding that call into their custom elisp, while `jiralib--get-account-sym` signals that it is meant to be for package use only.

I think I may pull your changes in if you/the other on-prem users can confirm your branch works well enough and fixes org-jira from being unusable.

Last note, your link in the original comment is pointing to a 404 - "org-mode" repo under your profile, should probably be "org-jira".

**Comment by 0l1ve** [comment] 2022-03-02 22:11
Sorry about the regressions and thank you again for the tips.  Lisp has never been my strong suite.  I agree it can end up being a hassle in the long term maintenance wise trying to keep track/test for both sets of apparent API calls. Not really sure how best to handle that at the moment though perhaps an automated testing can be set up by using https://hub.docker.com/r/atlassian/jira-software/  if it does allow basic Jira functionailty/rest API access.  Will have to look into that.

**Comment by logc** [comment] 2023-02-08 11:00
Let me also signal interest in the Server fork. My company only runs a Server instance at the moment. I can't offer a lot of support because Elisp is not my main expertise but for sure I can test functionality and report issues.

**Comment by ahungry** [comment] 2023-03-24 00:10
I'm going to close this, as it's more of a brainstorm/wishlist ticket - I don't have the time to support this, as it'd be an act of pure altruism, as I can't see that I'll ever be using a docker based jira (although if that changes, maybe I'll revisit the idea), and it'd add a scaling maintenance problem on what's currently there (cloud tested support).

Those types of altruistic FOSS efforts are more interesting and tolerable when it's one's "own idea" and not supporting an interface to a proprietary SASS site :laughing:

**Closed by ahungry** 2023-03-24 00:10 UTC
