### ISSUE TITLE
org-jira-update-issue fails with "Field 'X' cannot be set. It is not on the appropriate screen, or unknown."

### ISSUE THREAD

**Issue by pascalhaakmat** [ahungry/org-jira#152] opened 2018-10-08 09:10 UTC
org-jira-update-issue seems to fail on projects which don't have "components" or "priority" fields configured. 

```
HTTP/1.1 400 
Server: Atlassian Proxy/1.13.6.2
...

{"errorMessages":[],"errors":{"priority":"Field 'priority' cannot be set. It is not on the appropriate screen, or unknown.","components":"Field 'components' cannot be set. It is not on the appropriate screen, or unknown."}}

```

Perhaps the solution might be to add an org-jira variable which allows you to specify the fields to update?

**Comment by ahungry** [comment] 2018-10-28 04:08
Those should (and I believe at one time) were optional - so this is a regression most likely that needs to be fixed.

**Comment by mujo-hash** [comment] 2021-07-13 20:28
I have what appears to be another instance of this issue, expect for the components and reporter fields
```
"JIRA_ERROR REQUEST: "

"/rest/api/2/issue/OCD-324"

(:type "PUT" :data "{\"fields\":{\"components\":[],\"priority\":{\"id\":\"1\",\"name\":\"Highest\"},\"description\":\"Current issue: When a customer is completing a purchase and enters their address incorrectly in the fields, there is no validation to warn the client that they need to fix their mistakes. It allows the customer to complete their purchase. \\n  \\n  *Note:* Use this user ID for USPS.\\n  \\n  *USPS User ID: 251GEARU2117*\",\"assignee\":{\"id\":\"5ede5f7d6bd4b80aada1fef1\"},\"reporter\":{\"id\":null},\"summary\":\"No Address validation for cart checkout\",\"issuetype\":{\"id\":\"10006\",\"name\":\"Story\"}}}")

"JIRA_ERROR RESPONSE: "

((errorMessages . []) (errors (components . "Field 'components' cannot be set. It is not on the appropriate screen, or unknown.") (reporter . "Field 'reporter' cannot be set. It is not on the appropriate screen, or unknown.")))
```

**Comment by worldofgeese** [comment] 2021-07-19 09:16
My issue #257 is likely a duplicate of this issue.

**Comment by ahungry** [comment] 2021-07-19 22:42
This can be fixed with this custom now: `jiralib-update-issue-fields-exclude-list` - add the problematic fields in here, and they won't attempt to be synced.

**Closed by ahungry** 2021-07-19 22:42 UTC
Labels: bug
