### ISSUE TITLE
Problems with Creating new Issues

### ISSUE THREAD

**Issue by LeeRuns** [ahungry/org-jira#294] opened 2022-04-28 15:18 UTC
# Don't know if it is me or my emacs setup but I  cannot create new issues :(

# CASE 1: use org-jira-create-issue
3. m-x org-jira-create-issue
4. select project 
5. select task
6. error thrown
![image](https://user-images.githubusercontent.com/15914558/165785865-e384fc88-1a02-4c8e-acc7-363d6ea03da7.png)

# CASE 2: use org-jira-todo-to-jira
1. i write a "todo" in one of my org files
![image](https://user-images.githubusercontent.com/15914558/165785706-f35038c1-23f5-49dd-b5cc-7f6a7f49708f.png)
2. select my project 
3. select an issue type:
Worth noting this is where i see a bit of weird behavior. i have multiple projects, but at this point i have selected one.  Each project has 5 different issue types (Epic, Story, Task, Subtask, Bug). When the ivy tree pops up with issue type options, it loads 15 options, not 5.  
![image](https://user-images.githubusercontent.com/15914558/165787569-edc0798d-df1b-4549-93b7-6aeec42630f4.png)
4. regardless of the item i select i get this result
![image](https://user-images.githubusercontent.com/15914558/165787672-3d660953-c2df-4817-8a16-517ceb8c405e.png)

 
_if there is something I am doing wrong then chime in. I just want to be able to blast my TODO's up to jira_

# General Discussion + Fanboyness
I really like org-jira tool, I am shamelessly at the point where I can't imagine leaving emacs.  I know that to function in the working world we need to communicate with others, so jira is there... I am going to digress a bit now into a feature list.  Hopefully we can work together to get some of these done. My lisp is sh*t by comparison to @ahungry ahungry, but I will do what I can.

**Comment by LeeRuns** [comment] 2022-05-26 15:06
thread bump

**Comment by rand-fu** [comment] 2022-07-07 00:46
Hey @LeeRuns you found my [old issue](https://github.com/ahungry/org-jira/issues/279)! Apologies its been a while since I ran into this but seems like it could be related.

I thought this was due to the jira board I was working with at the time but I'm actually able to recreate the problem if I try to create a `subtask` using `org-jira-todo-to-jira`. It looks like this fails because there is not way to assign a parent issue to the task. That makes sense, but what I found was that after triggering an error in that way I could no longer do anything with org-jira and would see the same error message you are getting.  The behavior is the same with lots of issues types as options and notably several for subtasks. I havent dug into why that is but hopefully will have some time in the future.

Anyway the issue doesn't seem to be ivy or helm related. I didn't find another package in my setup impacting it either.

My original resolution was to remove org-jira, purge my existing org-jira dir and any files, remove it from my cache and repos list, clear it from recentf, close emacs completely then reinstall and re-enable org-jira in my private config. I'll try to find time to recreate and provide better steps for the resolution when I have access to my test system.

I've  also found it helpful at times to set the following when trying to debug org-jira or requests issues, in case it's helpful to you.

```
(setq request-log-level 'blather)
(setq request-message-level 'blather)
```

**Comment by ahungry** [comment] 2023-03-24 00:08
Thank you for the support @rand-fu and the original ticket info @LeeRuns - I think this is pretty stalled out - I can't think of anything obvious to investigation (nor can I reproduce on my end).

Hopefully it resolved, or you found a way to work around it - if you updated the code to fix it, feel free to share in a PR, otherwise (and even if so) I'm going to go ahead and close this out, as the ticket is quite old now.

**Closed by ahungry** 2023-03-24 00:08 UTC
